[Roslyn Analyzer - 2] Import Roslyn Analyzer using the environment variable
NuGet/NuGet.Jobs pull request #1012
Opened 2021-11-18 23:13 UTC by zhhyu

Now we use the environment variable to import the project from NuGetBuild repo for Roslyn Analyzer and its configuration.

2021-11-18 23:16 UTC, zhhyu commented on src/NuGetCDNRedirect/NuGetCDNRedirect.csproj
> +      <Version>3.6.0</Version>
Upgrade the package to be compatible with the latest Roslyn Analyzer.

2021-11-18 23:22 UTC, zhhyu commented on build.ps1
> +Invoke-BuildStep 'Removing .editorconfig file' { Remove-EditorconfigFile -Directory $PSScriptRoot } `
See https://github.com/NuGet/ServerCommon/pull/377

2021-11-19 18:53 UTC, dannyjdev requested changes
Just make sure to update $BuildBranchCommit once https://github.com/NuGet/ServerCommon/pull/377 is merged.

2021-11-19 19:37 UTC, agr commented on build.ps1
> +    [string]$BuildBranchCommit = '4e43763650ef1d3d7eb532484cc7889ce8cdfd86'
Make sure you update the hash once https://github.com/NuGet/ServerCommon/pull/377 is merged.

2021-11-19 19:37 UTC, agr approved these changes

2021-11-19 19:45 UTC, dannyjdev approved these changes

2021-11-20 00:00 UTC, merged