Db2AzureSearch changes for Search-by-TFM
NuGet/NuGet.Jobs pull request #1096
Opened 2022-09-29 23:48 UTC by advay26

Addresses https://github.com/NuGet/Engineering/issues/4575

*NOTE:* We are using a feature branch so that we can stack a few commits together before merging it into dev.

This change adds framework data to the Search Index through the Db2AzureSearch job:
* Create new index fields for 'Frameworks' and 'Tfms'
* Populate the 'Tfms' field with target framework data from the DB
* Map the same Tfms to their respective Framework generations for the 'Frameworks' field
* Add tests

2022-09-30 02:16 UTC, advay26 commented on tests/NuGet.Services.AzureSearch.Tests/HijackDocumentBuilderFacts.cs
> +      ""frameworks"": null,
I wanted to split the Db2AzureSearch and Catalog2AzureSearch work into 2 PRs for easier readability. To make this possible, I've had to put the 'frameworks' and 'tfms' fields as null in the Catalog test cases (rather than an array), as Catalog2AzureSearch is not currently processing this data. I will add the Catalog2AzureSearch changes, including tests, in the next PR.

2022-09-30 15:54 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs
> +        public string[] Frameworks { get; set; }
Any particular reason we put this on the BaseMetadataDocument? This document is used for both the hijack index and the search index IIRC. I don't think we need to put this on the hijack index, right?

2022-09-30 15:55 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs
> +        public string[] Frameworks { get; set; }
We should have code comments explaining which part of the TFM the "framework" is.

2022-09-30 15:55 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs
> +        public string[] Frameworks { get; set; }
Also, normalization format, examples, etc.

2022-09-30 15:55 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs
> +        public string[] Frameworks { get; set; }
(use XML docs)

2022-09-30 15:58 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/BaseDocumentBuilder.cs
> +                            .Where(f => !f.FrameworkName.IsUnsupported)
Probably worth filtering in only `IsSpecificFramework == true`, https://github.com/NuGet/NuGet.Client/blob/1a082949ae5b6da7ca2cce047396c53ae1afdde7/src/NuGet.Core/NuGet.Frameworks/NuGetFramework.cs#L433-L436. Thoughts @dannyjdev ?

2022-09-30 16:02 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/BaseDocumentBuilder.cs
> +                        frameworks.Add("netframework");
I see what we're going for here. We need a new string for .NET Framework because we treat it differently than .NET 5 and 6 right?

We're essentially inventing a generation moniker that disambiguates .NET 5+ and .NET Framework ("net" can't do this). I see we need this for the data layer (Azure Search documents) as well as the protocol. Keeping these two sets of strings (data layer and protocol) seems reasonable -- although it's not clear at this point if that's your intent since this is just the data layer and service changes are not in PR yet.

I think it's worth running this by Nikolche and Andy on the client team to make sure there is no existing strings to disambiguate between .NET Framework, .NET 5+, .NET Core, and .NET Standard.

Basically, if available, we should use some official string for these things.

2022-09-30 16:05 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/BaseDocumentBuilder.cs
> +                        frameworks.Add("netframework");
Also, please define string constants for these generation names and use those. They will likely be used in multiple places or are, at the very least, becoming part of our contract and shouldn't be hidden away in a method body.

2022-09-30 16:05 UTC, joelverhagen requested changes
Good so far, just have some comments about the generation name string constants.

2022-10-05 22:27 UTC, dannyjdev commented on src/NuGet.Services.AzureSearch/BaseDocumentBuilder.cs
> +                            .Where(f => !f.FrameworkName.IsUnsupported)
Yes, I think it's better to have `IsSpecificFramework` instead of `IsUnsupported`. On gallery we are already filtering the `any` TFM.

2022-10-05 22:35 UTC, advay26 commented on src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs
> +        public string[] Frameworks { get; set; }
I'd got this wrong, I've now put these fields in the SearchDocument

2022-10-05 22:35 UTC, advay26 commented on src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs
> +        public string[] Frameworks { get; set; }
I've added docs for the 2 new fields (now in SearchDocument.cs)

2022-10-05 22:38 UTC, advay26 commented on src/NuGet.Services.AzureSearch/BaseDocumentBuilder.cs
> +                        frameworks.Add("netframework");
I've created these constants in NuGetGallery https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery.Core/Services/AssetFrameworkHelper.cs#L116-#L128

2022-10-05 22:39 UTC, advay26 commented on src/NuGet.Services.AzureSearch/BaseDocumentBuilder.cs
> +                    case ".NETFramework":
I've changed up this switch case to use available constants where we can, and to use case-insensitive comparisons for these values.

2022-10-05 22:42 UTC, dannyjdev commented on src/NuGet.Services.AzureSearch/SearchDocumentBuilder.cs
> +                            .Where(f => f.FrameworkName.IsSpecificFramework)
Also, filter Portable Class Libraries [PackageFrameworkCompatibility.Create](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery.Core/Frameworks/PackageFrameworkCompatibilityFactory.cs#L41) (the `!f.IsPCL` part) since we are not going to support PCLs on this work. Make sure to update his on the `GetTfmsFromPackage` method as well.

2022-10-06 13:12 UTC, joelverhagen approved these changes

2022-10-07 19:09 UTC, dannyjdev approved these changes

2022-10-07 19:13 UTC, joelverhagen approved these changes

2022-10-07 19:24 UTC, merged