SearchService changes for Search-by-TFM
NuGet/NuGet.Jobs pull request #1103
Opened 2022-10-17 23:19 UTC by advay26

Addresses https://github.com/NuGet/Engineering/issues/4578

This change adds framework data to the Search Index through the Db2AzureSearch job:
* Accept new Frameworks and Tfms query parameters
* Construct filter strings with the selected Frameworks and Tfms
* Read new index fields in search response
* Add tests

2022-10-18 14:54 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/V2SearchRequest.cs
> +        public string Frameworks { get; set; }
This model is essentially the service layer model, meaning it is best for it to most accurately represent the respective data types. In other words, I think Frameworks and Tfms should be collection data types here (e.g. List) not a string that gets parsed later.

Consider `V2SortBy`. This is a string in the controller but is immediately parsed to an enum in the controller (the "view" layer in an API). 

Could you try the same for `Frameworks` and `Tfms`?

The meta point is that it's easier to reason about the code if you can make the data types match their True representation as soon as possible.

2022-10-18 14:56 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/V2SearchRequest.cs
> +        public string Frameworks { get; set; }
I personally like `IReadOnlyList` for this purpose since we know it won't need to be modified after initialization.

2022-10-18 14:56 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +            string frameworks = null,
In light of the comment above, this should become a list and probably be empty when the parameter is not included.

2022-10-18 14:59 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        private string GetFrameworksOrTfmsFilterString(string indexField, string frameworks)
This appears to have not sanitation or validation. I believe a user could craft a framework value that ends up being parsed as filter syntax not framework values (a la SQL injection).

How can we validate the frameworks and TFM values to ensure they are safe and only include expected characters?

2022-10-18 14:59 UTC, joelverhagen requested changes
I left some comments about input validation and data types for service layer models.

2022-10-19 00:18 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        private string GetFrameworksOrTfmsFilterString(string indexField, string frameworks)
This makes sense. I've added the same validation steps we use when we're writing values into the index: checking the framework generations against the 4 supported constants, and checking that the TFMs are supported frameworks.

2022-10-19 14:37 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +            IReadOnlyList<string> frameworks = default,
nit: IMO there is not much value in optional parameters on private methods. It's probably better to be explicit about parameters at all call sites.

2022-10-19 14:42 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +                if (framework == AssetFrameworkHelper.FrameworkGenerationIdentifiers.Net ||
consider a `static readonly` hash set which is a little easier to maintain.

2022-10-19 14:42 UTC, joelverhagen commented on src/NuGet.Services.SearchService.Core/Controllers/SearchController.cs
> +                Frameworks = frameworks == null ? null : frameworks.Split(','),
what if there are spaces before or after the comma separator? Or multiple consecutive spaces?

2022-10-19 14:43 UTC, joelverhagen commented on src/NuGet.Services.SearchService.Core/Controllers/SearchController.cs
> +            string frameworks = null,
This is the protocol change. We should update the README either in this PR or in a subsequent one.

2022-10-19 14:46 UTC, joelverhagen commented on tests/NuGet.Services.SearchService.Core.Tests/Controllers/SearchControllerFacts.cs
> +                Assert.Contains("net5.0", lastRequest.Tfms);
I think you can do `Equal` on sequences handles the ordering, length, and value comparison automatically. Your current test does not assert on ordering (not a hard requirement for ordering but it's probably best to assert the exact behavior until we have a reason to be permissive on ordering).

2022-10-19 14:47 UTC, joelverhagen commented on tests/NuGet.Services.SearchService.Core.Tests/Controllers/SearchControllerFacts.cs
> +                    tfms: "net5.0,netstandard2.1");
Consider testing some more edge cases for these values. This is an open API endpoint. People can put weird stuff here.

2022-10-19 14:49 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        private bool IsValidFrameworkOrTfm(string indexField, string framework)
For the `Tfms` flow, we're using the original (user provided) value not the normalized version. Consider changing `IsValidFrameworkOrTfm` to `NormalizeOrNull` method that normalizes the input and returns null on invalid, Then you can just filter null after calling it.

2022-10-19 14:50 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        private bool IsValidFrameworkOrTfm(string indexField, string framework)
BTW, the behavior we have here is to _ignore_ bad input instead of erroring. We could return an error to the user if the input is not valid instead of ignoring it silently.

In general search service ignores bad input which ... maybe isn't a great dev experience? We could opt to be more explicit here.

Thoughts?

2022-10-19 14:51 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/V2SearchRequest.cs
> +        public IReadOnlyList<string> Tfms { get; set; }
Should `Tfms` be a `NuGetFramework` not a `string`? This would essentially force us to do the `NuGetFramework` and would mean (hopefully) we're only doing this parsing once per request, per TFM string rather than potentially multiple times for validation then normalization.

2022-10-19 14:53 UTC, joelverhagen commented on src/NuGet.Services.SearchService.Core/Controllers/SearchController.cs
> +                Tfms = tfms == null ? null : tfms.Split(','),
Thoughts on passing down `Array.Empty` instead of null? Nulls mean null checking so using the shared empty array instance provided by `Array.Empty` can lead to safer and cleaner code sometimes.

2022-10-20 21:42 UTC, advay26 commented on tests/NuGet.Services.AzureSearch.Tests/SearchService/SearchParametersBuilderFacts.cs
> +                new object[] { new List<string> {"netframework"},
Instead of doing it at the stage where we construct the parameters, I'm now validating and normalizing the framework and tfm inputs at the Controller layer. This means that once the framework and tfm values reach here, they should already be normalized, so I've added more test cases, but in SearchControllerFacts.cs instead of here.

2022-10-20 21:43 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +                if (framework == AssetFrameworkHelper.FrameworkGenerationIdentifiers.Net ||
Done. This validation is now in ParameterUtilities.cs, at the Controller layer.

2022-10-20 21:47 UTC, advay26 commented on src/NuGet.Services.SearchService.Core/Controllers/SearchController.cs
> +                Frameworks = frameworks == null ? null : frameworks.Split(','),
What we need to do here is split by commas, then trim excess whitespace on either side of an entry, and then remove any empty entries. `Split` allows us to specify StringSplitOptions to trim whitespace and remove empty entries, but Trimming Entries is only available in .NET 5 and later. Since we would need to split, **then** trim, and **then** remove empty entries, we essentially need to do these steps separately (not using the Split overloads). I've done this now, but as separate explicit steps (in ParameterUtilities.cs)

2022-10-20 21:48 UTC, advay26 commented on src/NuGet.Services.SearchService.Core/Controllers/SearchController.cs
> +            string frameworks = null,
I've updated the Readme as part of this change. Let me know how it reads

2022-10-20 21:53 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/V2SearchRequest.cs
> +        public IReadOnlyList<string> Tfms { get; set; }
For now, I decided to keep this as a List of strings. In the Controller layer (See ParameterUtilities.cs), we can parse the filter inputs as Frameworks, validate them, and then write the normalized strings to the resulting List, all at once. We would only be doing this cast once for each entry in a request, and it would be somewhat easier to work with strings in the Service layer (allows us to reuse some filter string code between Frameworks and Tfms more easily, for example)

2022-10-20 21:55 UTC, advay26 commented on src/NuGet.Services.SearchService.Core/Controllers/SearchController.cs
> +                Frameworks = frameworks == null ? null : frameworks.Split(','),
I think it makes sense to do all the parsing, validating, and normalizing all in one place, and the Controller layer seems a better place for this. Regarding your comment on erroring on invalid inputs, doing these checks at a layer closer to the requester also seems like a better choice. What pros and cons were you thinking of?

2022-10-20 22:00 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        private bool IsValidFrameworkOrTfm(string indexField, string framework)
I've moved all the validating and normalizing code over to the Controller layer (ParameterUtilities.cs), and it looks a bit different now, so I'm not sure how the first comment applies. We are still ignoring invalid inputs rather than erroring with the current code though. We can flag invalid framework or tfm strings when we're validating them in the Controller. Do we have other examples of invalid parameter errors in Search? I'd like to see what the UI experience (and the code) for this might look like

2022-10-20 22:10 UTC, joelverhagen commented on src/NuGet.Services.SearchService.Core/Controllers/SearchController.cs
> +                Frameworks = frameworks == null ? null : frameworks.Split(','),
Pros of validation in the service layer: any user of the service layer gets the same validations for free. 

Pros of validation in the controller layer: you will probably need to do view-specific validation here anyway, it keeps your service layer clean of view-specific validations (such as comma stuff)

It's a little bit moot since we only have one user of the service layer (the controller)

2022-10-20 22:12 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +        private static readonly HashSet<string> FrameworkGenerationIdentifiers = new HashSet<string> { AssetFrameworkHelper.FrameworkGenerationIdentifiers.Net,
consider using a case insensitive comparer for the HashSet ctor. Might be a nice little UX improvement for the API since NuGetFramework in general is case insensitive.
https://nugettools.azurewebsites.net/6.0.0/parse-framework?framework=NET46

2022-10-20 22:13 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +                                                        .Select(f => new PackageFramework() { TargetFramework = f })
nit: You don't need `PackageFramework` at all right? Can't you use `NuGetFramework` directly?

2022-10-20 22:14 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +            return frameworks == null ? new List<string>() : frameworks
You can use Array.Empty instead of the first option in the ternary. This will reduce allocations over creating a new empty list each time.

2022-10-20 22:14 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        // Constructs filter strings for both Frameworks and Tfms.
nit: put this in an XML doc block not a normal comment block

2022-10-20 22:14 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        // indexField: Determines which field you are targeting
there is a `<param>` XML doc thing for this.

2022-10-20 22:15 UTC, joelverhagen commented on src/NuGet.Services.SearchService.Core/README.md
> +since it should be considered an implementation detail of NuGetGallery. External clients should use the document V3
👀 oops. thanks for this

2022-10-20 22:16 UTC, joelverhagen commented on tests/NuGet.Services.SearchService.Core.Tests/Controllers/SearchControllerFacts.cs
> +                Assert.Equal(new List<string>(), lastRequest.Frameworks);
nit: consider Assert.Same on Array.Empty, this is a strong assertion and states we don't allocate a new list for empty frameworks.

2022-10-20 22:17 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +                                                        .Where(f => f.FrameworkName.IsSpecificFramework && !f.FrameworkName.IsPCL)
🚫🥒
(PCLs are jokingly called pickles sometimes)

2022-10-20 22:17 UTC, joelverhagen approved these changes
Address comments then :shipit:

2022-10-20 22:52 UTC, zhhyu approved these changes

2022-10-20 23:20 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +            return frameworks == null ? new List<string>() : frameworks
List<string> does not cast easily to an Array. Should we be using Array<string> for Frameworks and Tfms in V2SearchRequest, and then move the code to use Arrays everywhere instead? https://github.com/NuGet/NuGet.Jobs/pull/1103#discussion_r998348368

2022-10-20 23:27 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +            return frameworks == null ? new List<string>() : frameworks
Both are IReadOnlyList though. You can cast one of the ternary sides to `(IReadOnlyList<string>)` and it should work

2022-10-20 23:29 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +        private static readonly HashSet<string> FrameworkGenerationIdentifiers = new HashSet<string> { AssetFrameworkHelper.FrameworkGenerationIdentifiers.Net,
Our current implementation is case insensitive right now (we use `ToLower()` on the inputs, and compare them to the HashSet values, which are all lowercase).

Even if we did use a case insensitive comparer for the HashSet, we would still need to normalize the input string (using `ToLower`) after comparing it against the HashSet right? Functionally, I don't think there's any difference, but making the HashSet use a non-default comparer might actually slow down perf in this case

2022-10-20 23:30 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +            return frameworks == null ? new List<string>() : frameworks
Is casting an empty Array to a List this way better than allocating a new List directly?

2022-10-20 23:32 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +                                                        .Select(f => new PackageFramework() { TargetFramework = f })
Yeah, I was struggling to parse the Tfm strings as NuGetFrameworks directly, so I was going through PackageFramework to do it. I've figured it out now, so I'll make that change in the next commit.

2022-10-20 23:35 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +            return frameworks == null ? new List<string>() : frameworks
Cast it to IReadOnlyList, not List.
https://dotnetfiddle.net/6nv6Za

And yes, it's better. Casting does not (typically) allocate on the heap.

2022-10-20 23:36 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchParametersBuilder.cs
> +        private bool IsValidFrameworkOrTfm(string indexField, string framework)
No examples right now. In general we don't error out on bad input, we ignore it. And the error would probably not be surfaced in the Gallery UI at all. It would be more for custom code against our APIs (3rd party devs)

2022-10-20 23:45 UTC, advay26 commented on tests/NuGet.Services.SearchService.Core.Tests/Controllers/SearchControllerFacts.cs
> +                Assert.Equal(new List<string>(), lastRequest.Frameworks);
I realized there's also an `Assert.Empty`, which seems like the best option here. Does that work?

2022-10-21 13:46 UTC, joelverhagen commented on tests/NuGet.Services.SearchService.Core.Tests/Controllers/SearchControllerFacts.cs
> +                Assert.Equal(new List<string>(), lastRequest.Frameworks);
It works, however it doesn't assert the shared instance is used like `Assert.Same` does. Not a big deal though, I'll leave it up to you.

2022-10-21 13:49 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +                                .Select(f => NuGetFramework.Parse(f))
Take a look at the code of `NuGetFramework`. There are some cases that throw instead of returning unspecified.
https://github.com/NuGet/NuGet.Client/blob/d1620d3bc77030d05e7e76b5adf06c33c4dc8374/src/NuGet.Core/NuGet.Frameworks/NuGetFrameworkFactory.cs#L137-L144

https://github.com/NuGet/NuGet.Client/blob/d1620d3bc77030d05e7e76b5adf06c33c4dc8374/src/NuGet.Core/NuGet.Frameworks/NuGetFrameworkFactory.cs#L247-L250

We may need to catch `ArgumentException` 😨. UTs should probably cover these to verify behavior over time.

2022-10-21 20:17 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +                                .Select(f => NuGetFramework.Parse(f))
I've done this and added tests as well. Let me know how it looks

2022-10-24 18:51 UTC, joelverhagen approved these changes

2022-10-24 18:56 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +        private static readonly HashSet<string> FrameworkGenerationIdentifiers = new HashSet<string> { AssetFrameworkHelper.FrameworkGenerationIdentifiers.Net,
Great point! You could do an all in one with a case insensitive Dictionary instead of a dictionary where the keys are allowed inputs and the values are the normalized inputs. This means you're not allocating for the `ToLower` but we're talking about micro-optimizations here without any benchmark :) go for what is easiest to read.

2022-10-25 20:04 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +        private static readonly HashSet<string> FrameworkGenerationIdentifiers = new HashSet<string> { AssetFrameworkHelper.FrameworkGenerationIdentifiers.Net,
I ran the benchmarking tool on 
(1) the original method with ToLower and a HashSet, 
(2) a case insensitive Dictionary (with normalized strings as values) with no ToLower, and
(3) a regular (case sensitive) Dictionary with no ToLower (This would not normalize inputs correctly, but I wanted to check its perf. This should be and was the quickest of the 3 methods).

The original method (1) was quicker than the Dictionary method (2) by about 5%. I'm guessing that the case insensitive comparer slows down the Dictionary access by longer than the ToLower allocation does.
![image](https://user-images.githubusercontent.com/82980589/197870177-d96f6cb6-f878-41b1-8853-8b357930b397.png)

2022-10-25 20:04 UTC, advay26 commented on src/NuGet.Services.AzureSearch/SearchService/Models/ParameterUtilities.cs
> +        private static readonly HashSet<string> FrameworkGenerationIdentifiers = new HashSet<string> { AssetFrameworkHelper.FrameworkGenerationIdentifiers.Net,
I also added duplicate checks to the code now, thanks for calling it out.

2022-10-27 18:57 UTC, merged