deprecation and vulnerability - add fields to search documents
NuGet/NuGet.Jobs pull request #1106
Opened 2022-10-27 23:25 UTC by camigthompson

Addresses: https://github.com/NuGet/Engineering/issues/4501

2022-10-27 23:42 UTC, drewgillies submitted a review, later dismissed
Some nits--the null checks are the critical pieces there but you may have covered this upstream.

2022-10-27 23:42 UTC, drewgillies commented on src/NuGet.Jobs.Db2AzureSearch/NuGet.Jobs.Db2AzureSearch.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
This is odd. :)

2022-10-27 23:42 UTC, drewgillies commented on src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs
> +
As is this. You can revert this file for cleanness.

2022-10-27 23:42 UTC, drewgillies commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                DeprecationInfo = result.DeprecationInfo.Message != null ? result.DeprecationInfo : null,
Should `DeprecationInfo` be null checked?

2022-10-27 23:42 UTC, drewgillies commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                DeprecationInfo = result.DeprecationInfo.Message != null ? result.DeprecationInfo : null,
And `Vulnerabilities`?

2022-10-28 14:12 UTC, joelverhagen commented
I think we should merge this into a feature branch. If this get's merged to `dev`, then taken to DEV, INT, then PROD, couldn't the existing service and jobs break since the C# models refer to Azure Search fields that don't exist in the running index? We can talk offline about the rollout/phasing strategy and use a similar approach as @advay26's search-by-TFM work.

2022-10-28 14:13 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/Models/SearchDocument.cs
> +        public AlternatePackage AlternatePkg { get; set; }
Does calling it `AlternatePackage` work? This abbreviation is not used in NuGet typically.

2022-10-28 14:13 UTC, joelverhagen commented on src/NuGet.Services.SearchService.Core/appsettings.json
> +}
nit: revert unnecessary change

2022-10-28 14:14 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchDocumentBuilder.cs
> +                document.DeprecationInfo = new Deprecation();
This is clearly placeholder code (which is fine for an incremental PR like this). Could you put a TODO linking to a GitHub issue that tracks the work that will put this in its final, expected state?

2022-10-28 14:15 UTC, joelverhagen requested changes
I left some small comments. Let's merge this to a feature branch, no `dev` since it's not production ready yet (more PRs will be needed).

2022-10-28 22:28 UTC, advay26 commented on src/NuGet.Services.AzureSearch/Models/SearchDocument.cs
> +        public AlternatePackage AlternatePkg { get; set; }
`AlternatePackageInfo` would also be consistent with `DeprecationInfo` if we want to separate the type from the variable name

2022-11-03 18:35 UTC, zhhyu commented on src/NuGet.Services.AzureSearch/Models/SearchDocument.cs
> +using System.Collections.Generic;
We always place System.* libraries as first ones.

2022-11-03 18:45 UTC, zhhyu commented on src/NuGet.Services.AzureSearch/SearchDocumentBuilder.cs
> +            Package package)
>package [](http://example.com/codeflow?start=20&length=7)

Is package used so far?

2022-11-09 13:30 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/V3SearchPackage.cs
> +        public List<Vulnerability> Vulnerabilities { get; set; }
We should decouple the Azure Search data models from the response models. This allows us to be _conscious_ of API/protocol changes apart from internal implementation details (model changes). Said another way, once we ship this API, we really change change the response model without coordination with the client software. But we're free to change how the Azure Search index is shaped as long as we roll it out safely (index rebuilds, new code + new index type thing).

2022-11-09 13:31 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/Models/SearchDocument.cs
> +        public AlternatePackage AlternatePkg { get; set; }
I'm curious what the benefit is of having the "Info" suffix on the name. Wouldn't `AlternatePackage` and `Deprecation` work for the property names?

2022-11-09 13:33 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                DeprecationInfo = (result.DeprecationInfo != null && result.DeprecationInfo.Message != null) ? result.DeprecationInfo : null,
Consider adding a private help method to do the Deprecation model mapping and another to do the vulnerabilities (or per vulnerability instance) mapping.

2022-11-09 19:06 UTC, camigthompson commented on src/NuGet.Services.AzureSearch/SearchService/Models/V3SearchPackage.cs
> +        public List<Vulnerability> Vulnerabilities { get; set; }
So essentially have separate Deprecation/Vulnerability types for V3SearchPackage and SearchDocument?

2022-11-09 22:32 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/V3SearchPackage.cs
> +        public List<Vulnerability> Vulnerabilities { get; set; }
That's right. There will be some minor differences, like `[JsonPropertyName(...)]` on the V3SearchPackage related models.

2022-11-14 19:07 UTC, camigthompson commented on src/NuGet.Services.AzureSearch/Models/SearchDocument.cs
> +        public AlternatePackage AlternatePkg { get; set; }
I was thinking that "Info" suffix just keeps the type and the variable name separate, but if it's unnecessary then I can make that change.

2022-11-17 22:18 UTC, zhhyu commented on src/NuGet.Services.AzureSearch/SearchService/Models/V3SearchDeprecation.cs
> +        [JsonPropertyName("alternatePackage")]
nit: let's remove the unnecessary lines here.

2022-11-17 22:19 UTC, zhhyu commented on src/NuGet.Services.AzureSearch/SearchService/Models/V3SearchVulnerability.cs
> +        [JsonPropertyName("advisoryUrl")]
nit: let's remove the unnecessary lines in this file.

2022-11-17 22:26 UTC, zhhyu commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                alternatepackage.Id = document.Deprecation.AlternatePackage.Id;
>.Id [](http://example.com/codeflow?start=75&length=3)

Is that possible that "AlternatePackage" is null here? If so, it will throw the exception. If "AlternatePackage" can be null as expected, the protection is needed here.

2022-11-17 22:36 UTC, agr commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                alternatepackage.Id = document.Deprecation.AlternatePackage.Id;
And it should be covered by tests.

2022-11-17 22:48 UTC, drewgillies commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                }
super-nit: Generally we go with `});` in these cases.

2022-11-17 22:48 UTC, drewgillies commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                    );
super-nit: Generally we go with `});` in these cases.

2022-11-18 19:28 UTC, zhhyu commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +            if (document.Deprecation != null)
Consider adding unit tests to cover all these corner cases (Deprecation + Vulnerabilities). This is to ensure that commits in the future will not break what we have today or at least get a warning before changing it.

2022-11-21 18:12 UTC, joelverhagen approved these changes
Add UTs for the `if` conditions added to response building (as @zhhyu mentioned) then :shipit:

2022-11-28 22:49 UTC, joelverhagen approved these changes

2022-11-28 23:13 UTC, advay26 approved these changes

2022-11-28 23:20 UTC, merged