[Search DV] Add deprecation and vulnerabilities to V2 search.
NuGet/NuGet.Jobs pull request #1134
Opened 2023-03-27 22:30 UTC by dannyjdev

### Changes
* V2Search page updated with deprecation and vulnerabilities properties.
* Updated `ToV2SearchPackage` method to include deprecation and vulnerabilities.
* 
Addresses: https://github.com/NuGet/Engineering/issues/4733

2023-03-29 14:14 UTC, joelverhagen commented on src/NuGet.Services.AzureSearch/SearchService/Models/V2SearchPackage.cs
> +        public Deprecation Deprecation { get; internal set; }
Why `internal set`?

2023-03-29 14:18 UTC, joelverhagen commented on tests/NuGet.Services.AzureSearch.Tests/SearchService/SearchResponseBuilderFacts.cs
> +          ""Severity"": 1
In the protocol spec this is shown as an int-string not a real int. This aligns with the current registration resource:
https://github.com/NuGet/Engineering/blob/main/Server.Specs/DeprecationsAndVulnerabilitiesInSearch.md#shape-of-the-returned-search-document

We should either adhere to the spec or get confirmation from client that it's okay to deviate in this way. IMO, a string is a little better, even if it's an int-string since it matches the current registration behavior.

2023-03-29 14:19 UTC, joelverhagen commented on tests/NuGet.Services.AzureSearch.Tests/SearchService/SearchResponseBuilderFacts.cs
> +            public void NullIconUrlWithFlatContainerIconsButNullOriginalIconUrl()
There should be UTs for null deprecation and null vulnerabilities.

2023-03-29 14:19 UTC, joelverhagen requested changes
I left a couple of small comments. Looks straight forward over all.

2023-03-31 18:55 UTC, dannyjdev commented on src/NuGet.Services.AzureSearch/SearchService/Models/V2SearchPackage.cs
> +        public Deprecation Deprecation { get; internal set; }
Didn't notice this, not sure why was added this way. I just removed it.

2023-03-31 18:57 UTC, dannyjdev commented on tests/NuGet.Services.AzureSearch.Tests/SearchService/SearchResponseBuilderFacts.cs
> +          ""Severity"": 1
For what I saw, in the end that property was added as int, you can check it here https://azuresearch-usnc.dev.nugettest.org/query?q=jquery.validation.

2023-03-31 18:57 UTC, dannyjdev commented on tests/NuGet.Services.AzureSearch.Tests/SearchService/SearchResponseBuilderFacts.cs
> +            public void NullIconUrlWithFlatContainerIconsButNullOriginalIconUrl()
Added multiple validations to be the same as the used on V3.

2023-03-31 20:01 UTC, joelverhagen commented on tests/NuGet.Services.AzureSearch.Tests/SearchService/SearchResponseBuilderFacts.cs
> +          ""Severity"": 1
@theot12 - looks like the v3 protocol has `int` severity.

2023-04-03 17:01 UTC, theot12 requested changes
Looks good! I left a comment about the deprecation and vulnerability classes used.

2023-04-19 21:42 UTC, theot12 commented on tests/NuGet.Services.AzureSearch.Tests/SearchService/SearchResponseBuilderFacts.cs
> +          ""Severity"": 1
@dannyjdev @joelverhagen The severity `int` in v3 seems to have been an oversight on my part. Let's stick with an int-string to not change what is currently being returned by registration. I will need to make that change in v3, but that shouldn't require another index rebuild.

2023-04-19 23:32 UTC, dannyjdev commented on src/NuGet.Services.AzureSearch/SearchService/Models/V2SearchPackage.cs
> +        public Vulnerability[] Vulnerabilities { get; set; }
Updated the code with your suggestion.

2023-04-19 23:54 UTC, theot12 reviewed
Started a conversation about the vulnerability severity `int` vs `string` discussion. Let's see how that plays out and change this PR accordingly.

2023-04-19 23:54 UTC, theot12 commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                deprecation.AlternatePackage = new V2SearchAlternatePackage { };
```suggestion
                deprecation.AlternatePackage = new V2SearchAlternatePackage();
```

2023-04-19 23:54 UTC, theot12 commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
>                  deprecation.AlternatePackage = new V3SearchAlternatePackage{};
I think this should actually look like this (as well as for V2). Correct me if I'm wrong!
```suggestion
                deprecation.AlternatePackage = new V3SearchAlternatePackage(); 
```

2023-04-20 00:10 UTC, dannyjdev commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
>                  deprecation.AlternatePackage = new V3SearchAlternatePackage{};
Yes, make sense, we are not assigning anything there.

2023-04-20 00:11 UTC, dannyjdev commented on src/NuGet.Services.AzureSearch/SearchService/SearchResponseBuilder.cs
> +                deprecation.AlternatePackage = new V2SearchAlternatePackage { };
Updated.

2023-04-25 19:22 UTC, theot12 approved these changes

2023-04-25 19:35 UTC, joelverhagen approved these changes

2023-04-25 20:04 UTC, merged