add roslyn anlyzer
NuGet/NuGet.Jobs pull request #921
Opened 2020-09-30 17:44 UTC by lyndaidaii

* add roslyn code analysis package reference to solution 
* add editorconfig to suppress different category warning and error except security
* add version of assemblyVersion to avoid build warning

Address: https://github.com/NuGet/Engineering/issues/3417

2020-09-30 18:01 UTC, lyndaidaii commented on src/NuGetCDNRedirect/NuGetCDNRedirect.csproj
> +      <Version>3.6.0</Version>
Update DotNetCompilerPlatform to latest version to create code analysis instance, current version has problem with installing roslyn analyzer package

2020-09-30 18:01 UTC, lyndaidaii commented on src/Stats.Warehouse/Stats.Warehouse.sqlproj
> +    <SqlCodeAnalysisRules>+!Microsoft.Rules.Data.SR0001;-Microsoft.Rules.Data.SR0004;-Microsoft.Rules.Data.SR0005;-Microsoft.Rules.Data.SR0006;-Microsoft.Rules.Data.SR0007;+!Microsoft.Rules.Data.SR00
Do we still need this code analysis?

2020-09-30 22:21 UTC, skofman1 commented
>     public class FixPackageHashHandler : IPackagesContainerHandler

Is this code still used? We can't use MD5 in the service, it's not SDL compliant.

---
Refers to: src/Catalog/FixPackageHashHandler.cs:18 in 75602bd. [](commit_id = 75602bd9dc55113d7ef510cf94ad9c0c9baed39d, deletion_comment = False)

2020-09-30 22:22 UTC, skofman1 commented
>     public class ValidatePackageHashHandler : IPackagesContainerHandler

Same. We should never use MD5

---
Refers to: src/Catalog/ValidatePackageHashHandler.cs:17 in 75602bd. [](commit_id = 75602bd9dc55113d7ef510cf94ad9c0c9baed39d, deletion_comment = False)

2020-09-30 22:24 UTC, skofman1 requested changes
:clock1:

2020-09-30 22:31 UTC, loic-sharma commented on Directory.Build.props
> +    <Version>3.0.0</Version>
Please indent lines 4-6

2020-09-30 22:32 UTC, loic-sharma commented on src/Catalog/Properties/AssemblyInfo.cs
> +﻿using System.Resources;
Please move this `using` below the copyright header.

2020-09-30 22:33 UTC, loic-sharma commented on src/Catalog/Properties/AssemblyInfo.cs
> +﻿using System.Resources;
Same comment for other occurrences later in this PR :)

2020-09-30 22:35 UTC, loic-sharma commented on src/NuGet.SupportRequests.Notifications/Properties/AssemblyInfo.cs
> +﻿using System.Resources;
Oops, it looks like we forgot to add the copyright header to this file. Could you add it please?

2020-09-30 22:39 UTC, loic-sharma commented on src/NuGetCDNRedirect/NuGetCDNRedirect.csproj
> +      <Version>3.6.0</Version>
Is this dependency needed? /cc @cristinamanum

2020-09-30 22:40 UTC, loic-sharma commented on src/NuGet.SupportRequests.Notifications/Properties/AssemblyInfo.cs
> +﻿using System.Resources;
Same comment for src/Stats.AzureCdnLogs.Common/Properties/AssemblyInfo.cs

2020-10-01 16:19 UTC, joelverhagen commented on src/NuGetCDNRedirect/NuGetCDNRedirect.csproj
> +      <Version>3.6.0</Version>
I'm pretty sure this is a default dependency in empty web projects. It's simple to verify the behavior of this app. Just deploy it (slot-swap will test endpoints) and manually test several redirects, such as `{app service base URL}/v3/index.json`.

2020-10-01 16:19 UTC, joelverhagen commented on src/Stats.Warehouse/Stats.Warehouse.sqlproj
> +    <SqlCodeAnalysisRules>+!Microsoft.Rules.Data.SR0001;-Microsoft.Rules.Data.SR0004;-Microsoft.Rules.Data.SR0005;-Microsoft.Rules.Data.SR0006;-Microsoft.Rules.Data.SR0007;+!Microsoft.Rules.Data.SR00
No idea, this predates me. If you remove it, what happens?

2020-10-01 16:20 UTC, joelverhagen commented on src/Stats.Warehouse/Stats.Warehouse.sqlproj
> +    <Compile Include="Properties\AssemblyInfo.cs" />
Can we generate assembly info for this project too then include `Assembly.*.cs` so we are consistent?

2020-10-01 16:20 UTC, joelverhagen commented on src/Validation.Symbols/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
Can we generate assembly info here to be consistent and include `AssemblyInfo.*.cs`?

2020-10-01 16:21 UTC, joelverhagen commented on src/Stats.Warehouse/Stats.Warehouse.sqlproj
> +    <Compile Include="Properties\AssemblyInfo.cs" />
You'd need to update the `build.ps1` to do this.

2020-10-02 03:37 UTC, lyndaidaii commented on src/Stats.Warehouse/Stats.Warehouse.sqlproj
> +    <SqlCodeAnalysisRules>+!Microsoft.Rules.Data.SR0001;-Microsoft.Rules.Data.SR0004;-Microsoft.Rules.Data.SR0005;-Microsoft.Rules.Data.SR0006;-Microsoft.Rules.Data.SR0007;+!Microsoft.Rules.Data.SR00
I guess I won't remove it. It was sql code analysis that not covered in Roslyn Analyzer. It will be nice to still keep it to catch something.

2020-10-02 03:44 UTC, lyndaidaii commented
> > ```
> > public class ValidatePackageHashHandler : IPackagesContainerHandler
> > ```
> 
> Same. We should never use MD5
> 
> Refers to: src/Catalog/ValidatePackageHashHandler.cs:17 in [75602bd](https://github.com/NuGet/NuGet.Jobs/commit/75602bd9dc55113d7ef510cf94ad9c0c9baed39d). [](commit_id = [75602bd](https://github.com/NuGet/NuGet.Jobs/commit/75602bd9dc55113d7ef510cf94ad9c0c9baed39d), deletion_comment = False)

This class being used in ProcessCatalogIndexEntryAsync, Also MD5 is being used multiple places. I think I will create another ticket  to deal with MD5

2020-10-02 04:05 UTC, lyndaidaii commented on src/Catalog/FixPackageHashHandler.cs
> +#pragma warning disable CA5351 // Do Not Use Broken Cryptographic Algorithms
`public class FixPackageHashHandler : IPackagesContainerHandler` is dead code? This class is being used in https://github.com/NuGet/NuGet.Jobs/blob/master/src/Catalog/PackagesContainerCatalogProcessor.cs#L57, this PackagesContainerCatalogProcessor is dead code too?

2020-10-14 22:59 UTC, lyndaidaii commented
Will have a separate PR to remove dead code.

2020-10-20 17:26 UTC, joelverhagen commented on src/NuGetCDNRedirect/NuGetCDNRedirect.csproj
> +      <Version>3.6.0</Version>
Please queue a build here:
https://devdiv.visualstudio.com/DevDiv/_build?definitionId=11105
And deploy the build here:
https://devdiv.visualstudio.com/DevDiv/_release?view=mine&definitionId=1581&_a=releases
to verify that CDNRedirect is still happy

2020-10-20 17:27 UTC, joelverhagen approved these changes
Merge deleted code PR, test CDN redirect deployment with your branch, then ship it.

2020-10-21 21:45 UTC, loic-sharma approved these changes

2020-10-21 22:37 UTC, lyndaidaii commented
Tested CDN redirect deployment with this branch.

2020-10-21 22:54 UTC, lyndaidaii commented on tests/NgTests/Properties/AssemblyInfo.cs
> +
remove this blank line

2020-10-21 22:54 UTC, lyndaidaii commented on tests/NuGet.Jobs.GitHubIndexer.Tests/Properties/AssemblyInfo.cs
> +﻿using System.Resources;
move to line 6

2020-10-21 22:56 UTC, lyndaidaii commented on tests/NuGet.Protocol.Catalog.Tests/Properties/AssemblyInfo.cs
> +﻿using System.Resources;
move to line 6

2020-10-22 18:38 UTC, merged