orchestrator save/deletereadme file to flat container
NuGet/NuGet.Jobs pull request #953
Opened 2021-01-20 02:56 UTC by lyndaidaii

* PackageStatusProcessor added logic to save readme files to flat container
* Added telemetry for readme file operations.
* ServerCommon version upgrade. (This need to be updated after https://github.com/NuGet/NuGetGallery/pull/8377 is merged)

2021-01-20 02:57 UTC, lyndaidaii commented on src/NuGet.Jobs.GitHubIndexer/NuGet.Jobs.GitHubIndexer.csproj
> +      <Version>4.4.6-gallery-2configuration-4385211</Version>
Need to be updated after https://github.com/NuGet/NuGetGallery/pull/8377 is merged

2021-01-20 02:58 UTC, lyndaidaii commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +            if (validatingEntity.EntityRecord.EmbeddedLicenseType != EmbeddedLicenseFileType.Absent || validatingEntity.EntityRecord.HasEmbeddedReadme)
Remove condition `validatingEntity.EntityRecord.HasEmbeddedReadme`

2021-01-21 22:22 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +                using (var packageStream = await _packageFileService.DownloadPackageFileToDiskAsync(validationSet))
We are downloading the package above. We shouldn't need to download it again. Consider putting both "extract" steps in the same downloading `using`.

2021-01-21 22:26 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +                    await _coreReadmeFileService.ExtractAndSaveReadmeFileAsync(validatingEntity.EntityRecord, packageStream);
just a note: this only saves to global storage, not China storage so if we ever want to make this V3 asset public/documented we would need to move this logic to catalog2dnx

2021-01-21 22:26 UTC, skofman1 commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +                using (var packageStream = await _packageFileService.DownloadPackageFileToDiskAsync(validationSet))
+1

2021-01-21 22:27 UTC, skofman1 commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +                    await _coreReadmeFileService.ExtractAndSaveReadmeFileAsync(validatingEntity.EntityRecord, packageStream);
Yup, but I don't think having it in China storage is a requirement right now.

2021-01-21 22:27 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +                    await _coreReadmeFileService.ExtractAndSaveReadmeFileAsync(validatingEntity.EntityRecord, packageStream);
Is the catalog2dnx work planned for soon? This code shouldn't go live until catalog2dnx is handling clean-up for when a package is deleted.

Package deletes do not flow into orchestrator at all.

2021-01-21 22:30 UTC, joelverhagen requested changes
⌚

2021-01-22 03:41 UTC, zhhyu commented
I am not sure why we change the decision to use Orchestrator rather than Catalog2Dnx here. I have same questions as above:
1. We still need the Catalog2Dnx job to clean up if the package should be deleted. If we put all the work (placing the readme into the flat container and deleting it from the flat container) there, it will be easier to maintain. I think the reason to place the license file using Orchestrator and show it to customers asap is because of some legal concerns;
2. One reason that we'd like to use the flat container is that we have a separate storage in China, and PM has some thoughts to support showing readmes in IDEs one day.
3. We are refreshing the Orchestrator. So maybe keeping this change inside the V3 pipeline will be easier.

2021-01-22 04:03 UTC, loic-sharma commented on src/NuGet.Services.Validation.Orchestrator/Job.cs
> +                .WithKeyedParameter(typeof(ICoreFileStorageService), CoreReadmeFileServiceBindingKey)
Is this right? It looks like you want the `ICoreFileStorage` that reads from the flat container, which currently uses the `CoreLicenseFileServiceBindingKey` key:

https://github.com/NuGet/NuGet.Jobs/blob/7dbf54e7a4c5d87a287ee1c171b74e7218f5ef47/src/NuGet.Services.Validation.Orchestrator/Job.cs#L455-L468

2021-02-03 18:02 UTC, joelverhagen approved these changes
Use official build of NuGetGallery.Core then :shipit:

2021-02-03 19:25 UTC, loic-sharma commented on src/NuGet.Services.Validation.Orchestrator/Telemetry/TelemetryService.cs
> +        private const string ExtractLicenseAndReadmeFileDuration = OrchestratorPrefix + "ExtractLicenseAndReadmeFileDuration";
Could you add a suffix to clarify the unit here?

```suggestion
        private const string ExtractLicenseAndReadmeFileDurationSeconds = OrchestratorPrefix + "ExtractLicenseAndReadmeFileDurationSeconds";
```

2021-02-03 19:26 UTC, loic-sharma approved these changes

2021-02-03 19:26 UTC, loic-sharma commented
Nice work! :)

2021-02-03 20:56 UTC, merged