Add readmeFile to catalog
NuGet/NuGet.Jobs pull request #954
Opened 2021-01-22 07:11 UTC by lyndaidaii

Add readmeFile to catalog

2021-01-26 23:57 UTC, joelverhagen commented on tests/CatalogTests/Helpers/UtilsTests.cs
> +        [InlineData("TestPackage.readmeFileOnly.0.4.2.nupkg.testdata")]
nit: for the one with "type" specified, we probably use double quotes in the test data since this is what pack will do:
`type="file"`
instead of 
`type='file'`

2021-01-26 23:58 UTC, joelverhagen commented on tests/CatalogTests/Helpers/UtilsTests.cs
> +        [InlineData("TestPackage.readmeFileOnly.0.4.2.nupkg.testdata")]
Would it be possible to test at a slightly higher level, like on the JSON produced instead? if no such "higher level" tests exist for you to mimic, don't worry about it, but personally I find the graph-based tests a little less trustworthy compared to looking at the actual JSON we produce.

2021-01-26 23:58 UTC, joelverhagen requested changes
⌚

2021-01-27 19:54 UTC, lyndaidaii commented on tests/CatalogTests/Helpers/UtilsTests.cs
> +        [InlineData("TestPackage.readmeFileOnly.0.4.2.nupkg.testdata")]
Checked the examples of LicenseExpression test nupkg, it uses single quotes here, which makes me a little confused
`    <license type='expression'>MIT</license>`

2021-01-27 20:12 UTC, lyndaidaii commented on tests/CatalogTests/Helpers/UtilsTests.cs
> +        [InlineData("TestPackage.readmeFileOnly.0.4.2.nupkg.testdata")]
I changed `type='file'` to `type="file"` in my test data

2021-02-03 20:28 UTC, lyndaidaii commented on tests/CatalogTests/Helpers/UtilsTests.cs
> +        [InlineData("TestPackage.readmeFileOnly.0.4.2.nupkg.testdata")]
added test that comparing the actual jjson file that we produce.
https://github.com/NuGet/NuGet.Jobs/blob/efa8fb2473353bbf3d18108ad626b16dae93ccd1/tests/CatalogTests/PackageCatalogItemTests.cs#L40

2021-02-04 01:50 UTC, joelverhagen commented on tests/CatalogTests/TestData/TestPackageReadmeFileWithFileType.json
> +  "readmeFile": "readme.md",
✔️

2021-02-04 01:50 UTC, joelverhagen approved these changes

2021-02-04 05:54 UTC, merged