[SAS Token] Validation jobs on demand sas token support.
NuGet/NuGet.Jobs pull request #965
Opened 2021-02-17 22:33 UTC by dannyjdev

Since we need to support on demand sas tokens from Validation.Orchestrator and ProcessSignature jobs I needed to perform the following changes:

1. Both jobs will have a new "sasdefinitions" section on their configuration containing the names of the sas definitions they will use.
2. ValidationPackageFileService and ProcessorPackageFileService where changed to support sas definitions for operations that creates on demand sas tokens.
3. PackageStatusProcessor, ValidationSetProcessor, ValidationSetProvider, and SignatureValidator where changed to provide the sas definition the previous services needs in order to retrieve a new sas token.
4. SharedAccessSignatureService was created to retrieve the sas definition secret.

2021-02-19 00:59 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +            IOptionsSnapshot<SasDefinitionConfiguration> sasDefinitionConfigurationAccessor,
nit: you can just call this `options` if you want 😃

2021-02-19 01:00 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/ValidationPackageFileService.cs
> +            if (string.IsNullOrEmpty(sasDefinition))
`== null` should be enough right? Why would empty string ever come in here?

2021-02-19 01:02 UTC, joelverhagen commented on src/Validation.Common.Job/SharedAccessSignatureService.cs
> +            return await _secretInjector.InjectAsync($"$${sasDefinition}$$");
You should be able to just use `ISecretReader` and use the secret name directly.

2021-02-19 01:03 UTC, joelverhagen commented on src/Validation.Common.Job/Storage/ProcessorPackageFileService.cs
> +            var sasToken = await _sharedAccessSignatureService.GetFromManagedStorageAccountAsync(sasDefinition);
I'm curious, what's the duration on this SAS definition? 7 days to match the current?

2021-02-19 01:04 UTC, joelverhagen commented on src/Validation.PackageSigning.ProcessSignature/Configuration/SasDefinitionConfiguration.cs
> +        public string SignatureValidatorSasDefinition { get; set; }
This could just be another property on `ProcessSignatureConfiguration` right? what's the benefit of a new class?

2021-02-19 01:05 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/Configuration/SasDefinitionConfiguration.cs
> +        public string PackageStatusProcessorSasDefinition { get; set; }
These could just be properties on `ValidationConfiguration` right? What's the benefit of a new class? It forces you to deal with more nullable objects this way.

2021-02-19 01:06 UTC, joelverhagen requested changes
Looks good overall, just have some questions and ideas to make the change a bit simpler.

2021-02-19 01:08 UTC, joelverhagen commented
Looks like there are some merge conflict.

2021-02-23 00:12 UTC, joelverhagen commented on src/Validation.PackageSigning.ProcessSignature/Configuration/SasDefinitionConfiguration.cs
> +        public string SignatureValidatorSasDefinition { get; set; }
I saw your comment on the other PR. This is fine and relatively consistent. Ignore my comment.

2021-02-23 00:12 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/Configuration/SasDefinitionConfiguration.cs
> +        public string PackageStatusProcessorSasDefinition { get; set; }
I saw your comment on the other PR. This is fine and relatively consistent. Ignore my comment.

2021-02-23 21:00 UTC, dannyjdev commented on src/Validation.Common.Job/SharedAccessSignatureService.cs
> +            return await _secretInjector.InjectAsync($"$${sasDefinition}$$");
The sas definition secret name is something like `<storageaccount>-<sasdefinitionname>`, I don't add the "$$" in configuration because the sas token would be injected starting the job instead of on demand. I tested removing the ""$$"" here and instead of retrieving the secret it retrieves the complete sas definition name.

2021-02-23 21:02 UTC, dannyjdev commented on src/NuGet.Services.Validation.Orchestrator/ValidationPackageFileService.cs
> +            if (string.IsNullOrEmpty(sasDefinition))
It's a public method, I just wanted to validate possible scenarios where we could reuse this method somewhere else or the sas configuration is just an empty string instead of null.

2021-02-23 21:03 UTC, dannyjdev commented on src/Validation.Common.Job/Storage/ProcessorPackageFileService.cs
> +            var sasToken = await _sharedAccessSignatureService.GetFromManagedStorageAccountAsync(sasDefinition);
Sas definitions are configured on our deployment repository, there you can see the scripts that creates them with the required time.

2021-02-23 21:15 UTC, joelverhagen commented on src/NuGet.Services.Validation.Orchestrator/ValidationPackageFileService.cs
> +            if (string.IsNullOrEmpty(sasDefinition))
Alright, seems fine. In general it's best to take the simplest reasonable solution possible. Given this is our own code that basically only we use (😭, unless?) we should be understanding the inputs coming in. An empty string SAS definition sounds like a bad configuration file in which case "gracefully" handling it in code is not necessary. We could just crash and then fix the config file. But this is rather philosophical and the amount of code is comparable. The one drawback is it makes me, the reader, think that empty strings are actually expected. I don't think they are. Null is the expected case when the SAS definition is not configured. AFAIK.

Leave it, it's not a big deal. Just wanted to clarify my thought process.

2021-02-23 21:18 UTC, joelverhagen commented on src/Validation.Common.Job/SharedAccessSignatureService.cs
> +            return await _secretInjector.InjectAsync($"$${sasDefinition}$$");
Sorry, not sure if I understand totally. I think I was too vague before perhaps. I'm suggesting to use the `ISecretReader` interface instead of `ISecretInjector`. This allows you to simply pass the secret name (whatever it may be) and get the secret value. Instead of going through the `$$` encoding. 
https://github.com/NuGet/ServerCommon/blob/5017f83e9620ab2e6dad45f8cb1491e30d9bee04/src/NuGet.Services.KeyVault/ISecretReader.cs#L11

2021-02-23 21:53 UTC, dannyjdev commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +            IOptionsSnapshot<SasDefinitionConfiguration> sasDefinitionConfigurationAccessor,
updated.

2021-02-23 23:06 UTC, joelverhagen commented on src/Validation.Common.Job/Storage/ProcessorPackageFileService.cs
> +            var sasToken = await _sharedAccessSignatureService.GetFromManagedStorageAccountAsync(sasDefinition);
Spoke offline. Looks good.

2021-02-24 01:34 UTC, dannyjdev commented on src/Validation.Common.Job/SharedAccessSignatureService.cs
> +            return await _secretInjector.InjectAsync($"$${sasDefinition}$$");
Changed ISecretInjector for ISecretReader.

2021-02-24 02:43 UTC, joelverhagen approved these changes

2021-02-24 06:32 UTC, loic-sharma commented on src/NuGet.Services.Validation.Orchestrator/PackageStatusProcessor.cs
> +            _sasDefinitionConfiguration = (options == null || options.Value == null) ? new SasDefinitionConfiguration() : options.Value;
When would `options` or `options.Value` be null? It looks like this type will always exist in the dependency injection container.

2021-02-24 06:36 UTC, loic-sharma commented on src/NuGet.Services.Validation.Orchestrator/ValidationPackageFileService.cs
> +        public async Task<Stream> DownloadPackageFileToDiskAsync(PackageValidationSet validationSet, string sasDefinition)
Is this ever called with a `sasDefinition` that's different than `SasDefinitionConfiguration.PackageStatusProcessorSasDefinition`? If no, should we just remove the parameter and read the configuration in this method instead?

2021-02-24 06:38 UTC, loic-sharma commented on src/NuGet.Services.Validation.Orchestrator/ValidationPackageFileService.cs
> +        public async Task<Stream> DownloadPackageFileToDiskAsync(PackageValidationSet validationSet, string sasDefinition)
Same comment for all the other methods. It seems they are only called with a single SAS definition each, can we pull the configuration one layer lower and remove these SAS definition parameters on all the methods in this class?

2021-02-24 19:33 UTC, dannyjdev commented on src/NuGet.Services.Validation.Orchestrator/ValidationPackageFileService.cs
> +        public async Task<Stream> DownloadPackageFileToDiskAsync(PackageValidationSet validationSet, string sasDefinition)
The `BackupPackageFileFromValidationSetPackageAsync` method it's called using 2 different sas definitions, that's why I didn't put those sas definitions as part of the Service implementation.

2021-02-24 19:50 UTC, merged